services:
  materinfo:
    image: ksugio/materinfo:latest
    #build: .
    environment:
      DEBUG: True
      DATABASE_URL: mysql://materinfouser:materinfopw@db:3306/materinfo
      STATIC_ROOT: /data/static
      MEDIA_ROOT: /data/media
      MEDIA_ACCEL_REDIRECT: True
      REPOS_ROOT: /data/repos
    ports:
      - "8000:8000"
    volumes:
      - materinfo-data:/data
    depends_on:
      - db
  nginx:
    image: ksugio/materinfo-nginx:latest
    #build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - materinfo-data:/data
    depends_on:
      - materinfo
  db:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: root2pass
      MARIADB_DATABASE: materinfo
      MARIADB_USER: materinfouser
      MARIADB_PASSWORD: materinfopw
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
  materinfo-data:

