# Generated by Django 4.2 on 2025-03-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='remoteurl',
        ),
    ]
