# Generated by Django 4.2 on 2025-03-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='remoteurl',
        ),
        migrations.AddField(
            model_name='sample',
            name='design',
            field=models.CharField(blank=True, max_length=36, verbose_name='Design'),
        ),
        migrations.AddField(
            model_name='sample',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
    ]
