# Generated by Django 4.2 on 2025-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_remove_sample_remoteurl_sample_design_sample_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='remoteauth',
            field=models.CharField(blank=True, max_length=10, verbose_name='Remote auth'),
        ),
        migrations.AddField(
            model_name='sample',
            name='remotelink',
            field=models.URLField(blank=True, verbose_name='Remote link'),
        ),
        migrations.AddField(
            model_name='sample',
            name='remotelog',
            field=models.TextField(blank=True, verbose_name='Remote log'),
        ),
        migrations.AddField(
            model_name='sample',
            name='remoteurl',
            field=models.URLField(blank=True, verbose_name='Remote URL'),
        ),
    ]
