# Generated by Django 4.2 on 2025-03-07 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Start Page')),
                ('end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Page')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('nimages', models.PositiveSmallIntegerField(default=0, verbose_name='Number of images')),
                ('tables', models.TextField(blank=True, verbose_name='Tables')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='article',
            name='booktitle',
            field=models.TextField(blank=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='cited',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Times cited'),
        ),
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=200, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='article',
            name='impact',
            field=models.FloatField(blank=True, null=True, verbose_name='Impact factor'),
        ),
        migrations.AddField(
            model_name='article',
            name='key',
            field=models.CharField(blank=True, max_length=20, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='article',
            name='month',
            field=models.CharField(blank=True, max_length=20, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='reference',
            name='data',
            field=models.TextField(blank=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='reference',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Latest Create'), (1, 'Earliest Create'), (2, 'Latest Update'), (3, 'Earliest Update'), (4, 'Latest'), (5, 'Earliest'), (6, 'Aescending Key'), (7, 'Descending Key')], default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='reference',
            name='pagesize',
            field=models.PositiveSmallIntegerField(choices=[(0, '10'), (1, '20'), (2, '50'), (3, '100'), (4, '200'), (5, '500')], default=0, verbose_name='Default Page Size'),
        ),
        migrations.AddField(
            model_name='reference',
            name='remoteauth',
            field=models.CharField(blank=True, max_length=10, verbose_name='Remote auth'),
        ),
        migrations.AddField(
            model_name='reference',
            name='remotelink',
            field=models.URLField(blank=True, verbose_name='Remote link'),
        ),
        migrations.AddField(
            model_name='reference',
            name='remotelog',
            field=models.TextField(blank=True, verbose_name='Remote log'),
        ),
        migrations.AddField(
            model_name='reference',
            name='startid',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Start ID'),
        ),
        migrations.AddField(
            model_name='reference',
            name='template',
            field=models.TextField(default='[{{ id }}] {{ author }}, "{{ title }}", {{ journal }}, Vol. {{ volume }}{% if number %}, {{ number }}{% endif %} ({{ year }}) pp. {{ page }}', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Article'), (1, 'Book'), (2, 'Booklet'), (3, 'InBook'), (4, 'InCollection'), (5, 'InProceedings'), (6, 'Manual'), (7, 'MastersThesis'), (8, 'Misc'), (9, 'PhdThesis'), (10, 'Proceedings'), (11, 'TechReport'), (12, 'Unpublished')], default=0, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('translate', models.PositiveSmallIntegerField(choices=[(0, 'DeepL API Free'), (1, 'DeepL API')], default=0, verbose_name='Translate')),
                ('sourcel', models.CharField(default='EN', max_length=10, verbose_name='Source Language')),
                ('targetl', models.CharField(default='JA', max_length=10, verbose_name='Target Language')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.text', verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='text',
            name='upper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.article', verbose_name='Article'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='Page')),
                ('scale', models.FloatField(default=1.0, verbose_name='Scale')),
                ('rotate', models.FloatField(default=0, verbose_name='Rotate angle')),
                ('startx', models.PositiveSmallIntegerField(default=0, verbose_name='Start x')),
                ('starty', models.PositiveSmallIntegerField(default=0, verbose_name='Start y')),
                ('endx', models.PositiveSmallIntegerField(default=0, verbose_name='End x')),
                ('endy', models.PositiveSmallIntegerField(default=0, verbose_name='End y')),
                ('zoom', models.PositiveSmallIntegerField(default=100, verbose_name='Zoom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.article', verbose_name='Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Digitizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('unique', models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data', models.TextField(blank=True, verbose_name='JSON Plot Data')),
                ('file', models.FileField(blank=True, null=True, upload_to=project.models.ModelUploadTo, verbose_name='CSV file')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.image', verbose_name='Figure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Start Page')),
                ('end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Page')),
                ('file', models.FileField(blank=True, upload_to=project.models.ModelUploadTo, verbose_name='File')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.article', verbose_name='Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
