# Generated by Django 4.2 on 2025-03-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_text_remove_article_page_article_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='template',
            field=models.TextField(default='[{{ id }}] {{ author }}, "{{ title }}", {{ journal }}, Vol. {{ volume }}{% if number %}, {{ number }}{% endif %} ({{ year }}) pp. {{ pages }}{% if doi %}, {{ doi }}{% endif %}', verbose_name='Template'),
        ),
    ]
