# Generated by Django 4.2 on 2025-03-28 23:58

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_reference_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
    ]
