# Generated by Django 4.2 on 2024-05-28 04:34

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_collect_unique_filter_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='clustering',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='reduction',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AlterField(
            model_name='regression',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
    ]
