# Generated by Django 4.2 on 2024-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_classification_unique_clustering_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustering',
            name='colormap',
            field=models.PositiveSmallIntegerField(choices=[(0, 'viridis'), (1, 'plasma'), (2, 'inferno'), (3, 'magma'), (4, 'cividis'), (5, 'Greys'), (6, 'Purples'), (7, 'Blues'), (8, 'Greens'), (9, 'Oranges'), (10, 'Reds'), (11, 'YlOrBr'), (12, 'YlOrRd'), (13, 'OrRd'), (14, 'PuRd'), (15, 'RdPu'), (16, 'BuPu'), (17, 'GnBu'), (18, 'PuBu'), (19, 'YlGnBu'), (20, 'PuBuGn'), (21, 'BuGn'), (22, 'YlGn'), (23, 'binary'), (24, 'gist_yarg'), (25, 'gist_gray'), (26, 'gray'), (27, 'bone'), (28, 'pink'), (29, 'spring'), (30, 'summer'), (31, 'autumn'), (32, 'winter'), (33, 'cool'), (34, 'Wistia'), (35, 'hot'), (36, 'afmhot'), (37, 'gist_heat'), (38, 'copper'), (39, 'PiYG'), (40, 'PRGn'), (41, 'BrBG'), (42, 'PuOr'), (43, 'RdGy'), (44, 'RdBu'), (45, 'RdYlBu'), (46, 'RdYlGn'), (47, 'Spectral'), (48, 'coolwarm'), (49, 'bwr'), (50, 'seismic'), (51, 'twilight'), (52, 'twilight_shifted'), (53, 'hsv'), (54, 'Pastel1'), (55, 'Pastel2'), (56, 'Paired'), (57, 'Accent'), (58, 'Dark2'), (59, 'Set1'), (60, 'Set2'), (61, 'Set3'), (62, 'tab10'), (63, 'tab20'), (64, 'tab20b'), (65, 'tab20c'), (66, 'flag'), (67, 'prism'), (68, 'ocean'), (69, 'gist_earth'), (70, 'terrain'), (71, 'gist_stern'), (72, 'gnuplot'), (73, 'gnuplot2'), (74, 'CMRmap'), (75, 'cubehelix'), (76, 'brg'), (77, 'gist_rainbow'), (78, 'rainbow'), (79, 'jet'), (80, 'turbo'), (81, 'nipy_spectral'), (82, 'gist_ncar')], default=0, verbose_name='Colormap'),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='colormap',
            field=models.PositiveSmallIntegerField(choices=[(0, 'viridis'), (1, 'plasma'), (2, 'inferno'), (3, 'magma'), (4, 'cividis'), (5, 'Greys'), (6, 'Purples'), (7, 'Blues'), (8, 'Greens'), (9, 'Oranges'), (10, 'Reds'), (11, 'YlOrBr'), (12, 'YlOrRd'), (13, 'OrRd'), (14, 'PuRd'), (15, 'RdPu'), (16, 'BuPu'), (17, 'GnBu'), (18, 'PuBu'), (19, 'YlGnBu'), (20, 'PuBuGn'), (21, 'BuGn'), (22, 'YlGn'), (23, 'binary'), (24, 'gist_yarg'), (25, 'gist_gray'), (26, 'gray'), (27, 'bone'), (28, 'pink'), (29, 'spring'), (30, 'summer'), (31, 'autumn'), (32, 'winter'), (33, 'cool'), (34, 'Wistia'), (35, 'hot'), (36, 'afmhot'), (37, 'gist_heat'), (38, 'copper'), (39, 'PiYG'), (40, 'PRGn'), (41, 'BrBG'), (42, 'PuOr'), (43, 'RdGy'), (44, 'RdBu'), (45, 'RdYlBu'), (46, 'RdYlGn'), (47, 'Spectral'), (48, 'coolwarm'), (49, 'bwr'), (50, 'seismic'), (51, 'twilight'), (52, 'twilight_shifted'), (53, 'hsv'), (54, 'Pastel1'), (55, 'Pastel2'), (56, 'Paired'), (57, 'Accent'), (58, 'Dark2'), (59, 'Set1'), (60, 'Set2'), (61, 'Set3'), (62, 'tab10'), (63, 'tab20'), (64, 'tab20b'), (65, 'tab20c'), (66, 'flag'), (67, 'prism'), (68, 'ocean'), (69, 'gist_earth'), (70, 'terrain'), (71, 'gist_stern'), (72, 'gnuplot'), (73, 'gnuplot2'), (74, 'CMRmap'), (75, 'cubehelix'), (76, 'brg'), (77, 'gist_rainbow'), (78, 'rainbow'), (79, 'jet'), (80, 'turbo'), (81, 'nipy_spectral'), (82, 'gist_ncar')], default=0, verbose_name='Colormap'),
        ),
    ]
