# Generated by Django 4.2 on 2025-03-07 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collect', '0004_alter_clustering_colormap_alter_reduction_colormap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classshap',
            name='test_size',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='remoteurl',
        ),
        migrations.RemoveField(
            model_name='regreshap',
            name='test_size',
        ),
        migrations.AddField(
            model_name='classification',
            name='randomts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Test random state'),
        ),
        migrations.AddField(
            model_name='classification',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='classification',
            name='testsize',
            field=models.FloatField(default=0.0, verbose_name='Test Size'),
        ),
        migrations.AddField(
            model_name='classshap',
            name='kmeans',
            field=models.PositiveIntegerField(default=10, verbose_name='K Means for Kernel Explainer'),
        ),
        migrations.AddField(
            model_name='classshap',
            name='nsample',
            field=models.PositiveIntegerField(default=200, verbose_name='N Sample for Kernel Explainer'),
        ),
        migrations.AddField(
            model_name='classshap',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='classshap',
            name='use_kernel',
            field=models.BooleanField(default=False, verbose_name='Use Kernel Explainer'),
        ),
        migrations.AddField(
            model_name='clustering',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='inverse',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='regreshap',
            name='kmeans',
            field=models.PositiveIntegerField(default=10, verbose_name='K Means for Kernel Explainer'),
        ),
        migrations.AddField(
            model_name='regreshap',
            name='nsample',
            field=models.PositiveIntegerField(default=200, verbose_name='N Sample for Kernel Explainer'),
        ),
        migrations.AddField(
            model_name='regreshap',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='regreshap',
            name='use_kernel',
            field=models.BooleanField(default=False, verbose_name='Use Kernel Explainer'),
        ),
        migrations.AddField(
            model_name='regression',
            name='randomts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Test random state'),
        ),
        migrations.AddField(
            model_name='regression',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='regression',
            name='testsize',
            field=models.FloatField(default=0.0, verbose_name='Test Size'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'joblib'), (1, 'onnx')], default=0, verbose_name='File type'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='random',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Split random state'),
        ),
        migrations.AlterField(
            model_name='regression',
            name='file2_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'joblib'), (1, 'onnx')], default=0, verbose_name='File2 type'),
        ),
        migrations.AlterField(
            model_name='regression',
            name='random',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Split random state'),
        ),
        migrations.CreateModel(
            name='RegrePred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Valid'), (1, 'Invalid'), (2, 'Pending')], default=0, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('file', models.FileField(upload_to=project.models.ModelUploadTo, verbose_name='File')),
                ('objective', models.CharField(blank=True, max_length=250, verbose_name='Objective column')),
                ('drop', models.CharField(blank=True, max_length=250, verbose_name='Drop columns')),
                ('results', models.TextField(blank=True, verbose_name='JSON Results')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.regression', verbose_name='Regression')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Valid'), (1, 'Invalid'), (2, 'Pending')], default=0, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('file', models.FileField(upload_to=project.models.ModelUploadTo, verbose_name='File')),
                ('objective', models.CharField(blank=True, max_length=250, verbose_name='Objective column')),
                ('drop', models.CharField(blank=True, max_length=250, verbose_name='Drop columns')),
                ('results', models.TextField(blank=True, verbose_name='JSON Results')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.classification', verbose_name='Classification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
