# Generated by Django 4.2 on 2025-03-28 23:58

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_remove_classshap_test_size_remove_collect_remoteurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpred',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='correlation',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='inverse',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='regrepred',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
    ]
