# Generated by Django 4.2 on 2025-03-28 23:58

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_remoteurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.ModelUploadTo, verbose_name='PDF file'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Markdown'), (1, 'LaTex')], default=0, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='diff',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='filename', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='svg2pdf',
            field=models.BooleanField(default=False, verbose_name='SVG to PDF'),
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, max_length=256, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.UpperModelUploadTo, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_upper', to='article.article', verbose_name='Article'),
        ),
    ]
