# Generated by Django 4.2 on 2025-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_file_title_article_comment_article_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='remoteauth',
            field=models.CharField(blank=True, max_length=10, verbose_name='Remote auth'),
        ),
        migrations.AddField(
            model_name='article',
            name='remotelink',
            field=models.URLField(blank=True, verbose_name='Remote link'),
        ),
        migrations.AddField(
            model_name='article',
            name='remotelog',
            field=models.TextField(blank=True, verbose_name='Remote log'),
        ),
        migrations.AddField(
            model_name='article',
            name='remoteurl',
            field=models.URLField(blank=True, verbose_name='Remote URL'),
        ),
    ]
