# Generated by Django 4.2 on 2024-05-28 04:01

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_imfp_prefix_alter_ln2d_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='angle_max',
        ),
        migrations.RemoveField(
            model_name='size',
            name='angle_mean',
        ),
        migrations.RemoveField(
            model_name='size',
            name='angle_median',
        ),
        migrations.RemoveField(
            model_name='size',
            name='angle_min',
        ),
        migrations.RemoveField(
            model_name='size',
            name='angle_std',
        ),
        migrations.RemoveField(
            model_name='size',
            name='areafraction',
        ),
        migrations.RemoveField(
            model_name='size',
            name='aspectratio_max',
        ),
        migrations.RemoveField(
            model_name='size',
            name='aspectratio_mean',
        ),
        migrations.RemoveField(
            model_name='size',
            name='aspectratio_median',
        ),
        migrations.RemoveField(
            model_name='size',
            name='aspectratio_min',
        ),
        migrations.RemoveField(
            model_name='size',
            name='aspectratio_std',
        ),
        migrations.RemoveField(
            model_name='size',
            name='circularity_max',
        ),
        migrations.RemoveField(
            model_name='size',
            name='circularity_mean',
        ),
        migrations.RemoveField(
            model_name='size',
            name='circularity_median',
        ),
        migrations.RemoveField(
            model_name='size',
            name='circularity_min',
        ),
        migrations.RemoveField(
            model_name='size',
            name='circularity_std',
        ),
        migrations.RemoveField(
            model_name='size',
            name='diameter_max',
        ),
        migrations.RemoveField(
            model_name='size',
            name='diameter_mean',
        ),
        migrations.RemoveField(
            model_name='size',
            name='diameter_median',
        ),
        migrations.RemoveField(
            model_name='size',
            name='diameter_min',
        ),
        migrations.RemoveField(
            model_name='size',
            name='diameter_std',
        ),
        migrations.RemoveField(
            model_name='size',
            name='longside_max',
        ),
        migrations.RemoveField(
            model_name='size',
            name='longside_mean',
        ),
        migrations.RemoveField(
            model_name='size',
            name='longside_median',
        ),
        migrations.RemoveField(
            model_name='size',
            name='longside_min',
        ),
        migrations.RemoveField(
            model_name='size',
            name='longside_std',
        ),
        migrations.RemoveField(
            model_name='size',
            name='narrowside_max',
        ),
        migrations.RemoveField(
            model_name='size',
            name='narrowside_mean',
        ),
        migrations.RemoveField(
            model_name='size',
            name='narrowside_median',
        ),
        migrations.RemoveField(
            model_name='size',
            name='narrowside_min',
        ),
        migrations.RemoveField(
            model_name='size',
            name='narrowside_std',
        ),
        migrations.RemoveField(
            model_name='size',
            name='numberdensity',
        ),
        migrations.AddField(
            model_name='filter',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='image',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='imfp',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='ln2d',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
        migrations.AddField(
            model_name='size',
            name='results',
            field=models.TextField(blank=True, verbose_name='JSON Results'),
        ),
        migrations.AddField(
            model_name='size',
            name='roiarea',
            field=models.FloatField(blank=True, null=True, verbose_name='ROI Area (px)'),
        ),
        migrations.AddField(
            model_name='size',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
    ]
