# Generated by Django 4.2 on 2024-02-27 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('xlabel', models.CharField(blank=True, max_length=100, verbose_name='X Label')),
                ('ylabel', models.CharField(blank=True, max_length=100, verbose_name='Y Label')),
                ('xmin', models.FloatField(blank=True, null=True, verbose_name='X Min')),
                ('xmax', models.FloatField(blank=True, null=True, verbose_name='X Max')),
                ('ymin', models.FloatField(blank=True, null=True, verbose_name='Y Min')),
                ('ymax', models.FloatField(blank=True, null=True, verbose_name='Y Max')),
                ('legend', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Best'), (2, 'UpperRight'), (3, 'UpperLeft'), (4, 'LowerLeft'), (5, 'LowerRight')], default=0, verbose_name='Legend')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Valid'), (1, 'Invalid'), (2, 'Pending')], default=0, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('ncol', models.PositiveSmallIntegerField(default=1, verbose_name='N Column')),
                ('sizex', models.FloatField(default=6.4, verbose_name='Size X')),
                ('sizey', models.FloatField(default=4.8, verbose_name='Size Y')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
                ('columnx', models.CharField(max_length=100, verbose_name='Column X')),
                ('columny', models.CharField(blank=True, max_length=100, verbose_name='Column Y')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Line'), (1, 'LineMarker'), (2, 'Scatter'), (3, 'Bar'), (4, 'Histgram')], default=0, verbose_name='Type')),
                ('color', models.PositiveSmallIntegerField(choices=[(0, 'b'), (1, 'g'), (2, 'r'), (3, 'c'), (4, 'm'), (5, 'y'), (6, 'k'), (7, 'w'), (8, 'black'), (9, 'dimgray'), (10, 'dimgrey'), (11, 'gray'), (12, 'grey'), (13, 'darkgray'), (14, 'darkgrey'), (15, 'silver'), (16, 'lightgray'), (17, 'lightgrey'), (18, 'gainsboro'), (19, 'whitesmoke'), (20, 'white'), (21, 'snow'), (22, 'rosybrown'), (23, 'lightcoral'), (24, 'indianred'), (25, 'brown'), (26, 'firebrick'), (27, 'maroon'), (28, 'darkred'), (29, 'red'), (30, 'mistyrose'), (31, 'salmon'), (32, 'tomato'), (33, 'darksalmon'), (34, 'coral'), (35, 'orangered'), (36, 'lightsalmon'), (37, 'sienna'), (38, 'seashell'), (39, 'chocolate'), (40, 'saddlebrown'), (41, 'sandybrown'), (42, 'peachpuff'), (43, 'peru'), (44, 'linen'), (45, 'bisque'), (46, 'darkorange'), (47, 'burlywood'), (48, 'antiquewhite'), (49, 'tan'), (50, 'navajowhite'), (51, 'blanchedalmond'), (52, 'papayawhip'), (53, 'moccasin'), (54, 'orange'), (55, 'wheat'), (56, 'oldlace'), (57, 'floralwhite'), (58, 'darkgoldenrod'), (59, 'goldenrod'), (60, 'cornsilk'), (61, 'gold'), (62, 'lemonchiffon'), (63, 'khaki'), (64, 'palegoldenrod'), (65, 'darkkhaki'), (66, 'ivory'), (67, 'beige'), (68, 'lightyellow'), (69, 'lightgoldenrodyellow'), (70, 'olive'), (71, 'yellow'), (72, 'olivedrab'), (73, 'yellowgreen'), (74, 'darkolivegreen'), (75, 'greenyellow'), (76, 'chartreuse'), (77, 'lawngreen'), (78, 'honeydew'), (79, 'darkseagreen'), (80, 'palegreen'), (81, 'lightgreen'), (82, 'forestgreen'), (83, 'limegreen'), (84, 'darkgreen'), (85, 'green'), (86, 'lime'), (87, 'seagreen'), (88, 'mediumseagreen'), (89, 'springgreen'), (90, 'mintcream'), (91, 'mediumspringgreen'), (92, 'mediumaquamarine'), (93, 'aquamarine'), (94, 'turquoise'), (95, 'lightseagreen'), (96, 'mediumturquoise'), (97, 'azure'), (98, 'lightcyan'), (99, 'paleturquoise'), (100, 'darkslategray'), (101, 'darkslategrey'), (102, 'teal'), (103, 'darkcyan'), (104, 'aqua'), (105, 'cyan'), (106, 'darkturquoise'), (107, 'cadetblue'), (108, 'powderblue'), (109, 'lightblue'), (110, 'deepskyblue'), (111, 'skyblue'), (112, 'lightskyblue'), (113, 'steelblue'), (114, 'aliceblue'), (115, 'dodgerblue'), (116, 'lightslategray'), (117, 'lightslategrey'), (118, 'slategray'), (119, 'slategrey'), (120, 'lightsteelblue'), (121, 'cornflowerblue'), (122, 'royalblue'), (123, 'ghostwhite'), (124, 'lavender'), (125, 'midnightblue'), (126, 'navy'), (127, 'darkblue'), (128, 'mediumblue'), (129, 'blue'), (130, 'slateblue'), (131, 'darkslateblue'), (132, 'mediumslateblue'), (133, 'mediumpurple'), (134, 'rebeccapurple'), (135, 'blueviolet'), (136, 'indigo'), (137, 'darkorchid'), (138, 'darkviolet'), (139, 'mediumorchid'), (140, 'thistle'), (141, 'plum'), (142, 'violet'), (143, 'purple'), (144, 'darkmagenta'), (145, 'fuchsia'), (146, 'magenta'), (147, 'orchid'), (148, 'mediumvioletred'), (149, 'deeppink'), (150, 'hotpink'), (151, 'lavenderblush'), (152, 'palevioletred'), (153, 'crimson'), (154, 'pink'), (155, 'lightpink')], default=0, verbose_name='Color')),
                ('edgecolor', models.PositiveSmallIntegerField(choices=[(0, 'b'), (1, 'g'), (2, 'r'), (3, 'c'), (4, 'm'), (5, 'y'), (6, 'k'), (7, 'w'), (8, 'black'), (9, 'dimgray'), (10, 'dimgrey'), (11, 'gray'), (12, 'grey'), (13, 'darkgray'), (14, 'darkgrey'), (15, 'silver'), (16, 'lightgray'), (17, 'lightgrey'), (18, 'gainsboro'), (19, 'whitesmoke'), (20, 'white'), (21, 'snow'), (22, 'rosybrown'), (23, 'lightcoral'), (24, 'indianred'), (25, 'brown'), (26, 'firebrick'), (27, 'maroon'), (28, 'darkred'), (29, 'red'), (30, 'mistyrose'), (31, 'salmon'), (32, 'tomato'), (33, 'darksalmon'), (34, 'coral'), (35, 'orangered'), (36, 'lightsalmon'), (37, 'sienna'), (38, 'seashell'), (39, 'chocolate'), (40, 'saddlebrown'), (41, 'sandybrown'), (42, 'peachpuff'), (43, 'peru'), (44, 'linen'), (45, 'bisque'), (46, 'darkorange'), (47, 'burlywood'), (48, 'antiquewhite'), (49, 'tan'), (50, 'navajowhite'), (51, 'blanchedalmond'), (52, 'papayawhip'), (53, 'moccasin'), (54, 'orange'), (55, 'wheat'), (56, 'oldlace'), (57, 'floralwhite'), (58, 'darkgoldenrod'), (59, 'goldenrod'), (60, 'cornsilk'), (61, 'gold'), (62, 'lemonchiffon'), (63, 'khaki'), (64, 'palegoldenrod'), (65, 'darkkhaki'), (66, 'ivory'), (67, 'beige'), (68, 'lightyellow'), (69, 'lightgoldenrodyellow'), (70, 'olive'), (71, 'yellow'), (72, 'olivedrab'), (73, 'yellowgreen'), (74, 'darkolivegreen'), (75, 'greenyellow'), (76, 'chartreuse'), (77, 'lawngreen'), (78, 'honeydew'), (79, 'darkseagreen'), (80, 'palegreen'), (81, 'lightgreen'), (82, 'forestgreen'), (83, 'limegreen'), (84, 'darkgreen'), (85, 'green'), (86, 'lime'), (87, 'seagreen'), (88, 'mediumseagreen'), (89, 'springgreen'), (90, 'mintcream'), (91, 'mediumspringgreen'), (92, 'mediumaquamarine'), (93, 'aquamarine'), (94, 'turquoise'), (95, 'lightseagreen'), (96, 'mediumturquoise'), (97, 'azure'), (98, 'lightcyan'), (99, 'paleturquoise'), (100, 'darkslategray'), (101, 'darkslategrey'), (102, 'teal'), (103, 'darkcyan'), (104, 'aqua'), (105, 'cyan'), (106, 'darkturquoise'), (107, 'cadetblue'), (108, 'powderblue'), (109, 'lightblue'), (110, 'deepskyblue'), (111, 'skyblue'), (112, 'lightskyblue'), (113, 'steelblue'), (114, 'aliceblue'), (115, 'dodgerblue'), (116, 'lightslategray'), (117, 'lightslategrey'), (118, 'slategray'), (119, 'slategrey'), (120, 'lightsteelblue'), (121, 'cornflowerblue'), (122, 'royalblue'), (123, 'ghostwhite'), (124, 'lavender'), (125, 'midnightblue'), (126, 'navy'), (127, 'darkblue'), (128, 'mediumblue'), (129, 'blue'), (130, 'slateblue'), (131, 'darkslateblue'), (132, 'mediumslateblue'), (133, 'mediumpurple'), (134, 'rebeccapurple'), (135, 'blueviolet'), (136, 'indigo'), (137, 'darkorchid'), (138, 'darkviolet'), (139, 'mediumorchid'), (140, 'thistle'), (141, 'plum'), (142, 'violet'), (143, 'purple'), (144, 'darkmagenta'), (145, 'fuchsia'), (146, 'magenta'), (147, 'orchid'), (148, 'mediumvioletred'), (149, 'deeppink'), (150, 'hotpink'), (151, 'lavenderblush'), (152, 'palevioletred'), (153, 'crimson'), (154, 'pink'), (155, 'lightpink')], default=0, verbose_name='Edge color')),
                ('linewidth', models.FloatField(default=1.0, verbose_name='Line width')),
                ('linestyle', models.PositiveSmallIntegerField(choices=[(0, 'solid'), (1, 'loosely dotted'), (2, 'dotted'), (3, 'densely dotted'), (4, 'loosely dashed'), (5, 'dashed'), (6, 'densely dashed'), (7, 'loosely dashdotted'), (8, 'dashdotted'), (9, 'densely dashdotted'), (10, 'loosely dashdotdotted'), (11, 'dashdotdotted'), (12, 'densely dashdotdotted')], default=0, verbose_name='Line style')),
                ('marker', models.PositiveSmallIntegerField(choices=[(0, 'point'), (1, 'pixel'), (2, 'circle'), (3, 'triangle_down'), (4, 'triangle_up'), (5, 'triangle_left'), (6, 'triangle_right'), (7, 'tri_down'), (8, 'tri_up'), (9, 'tri_left'), (10, 'tri_right'), (11, 'octagon'), (12, 'square'), (13, 'pentagon'), (14, 'star'), (15, 'hexagon1'), (16, 'hexagon2'), (17, 'plus'), (18, 'cross'), (19, 'diamond'), (20, 'thin_diamond'), (21, 'vline'), (22, 'hline')], default=0, verbose_name='Marker')),
                ('markersize', models.PositiveSmallIntegerField(default=20, verbose_name='Marker size')),
                ('bins', models.PositiveSmallIntegerField(default=10, verbose_name='Bins')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Label')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.area', verbose_name='Plot area')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.models.FileSearch),
        ),
        migrations.AddField(
            model_name='area',
            name='upper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.plot', verbose_name='Plot'),
        ),
    ]
