# Generated by Django 4.2 on 2025-03-28 23:58

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_item_colormap_item_columnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.ModelUploadTo, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='plot',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SVG'), (1, 'PNG'), (2, 'JPEG'), (3, 'PDF'), (4, 'EPS')], default=0, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='plot',
            name='unique',
            field=models.CharField(default=project.models.UniqueStr, max_length=36, verbose_name='Unique String'),
        ),
    ]
