# Generated by Django 4.2 on 2025-03-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='remoteauth',
            field=models.CharField(blank=True, max_length=10, verbose_name='Remote auth'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='remotelink',
            field=models.URLField(blank=True, verbose_name='Remote link'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='remotelog',
            field=models.TextField(blank=True, verbose_name='Remote log'),
        ),
    ]
