# Generated by Django 4.2 on 2024-02-27 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('prefix', models.PositiveIntegerField(default=0, verbose_name='Prefix')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Valid'), (1, 'Invalid'), (2, 'Pending')], default=0, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('fraction', models.FloatField(blank=True, null=True, verbose_name='Fraction')),
                ('file', models.FileField(blank=True, upload_to=project.models.ModelUploadTo, verbose_name='File')),
                ('percent_in', models.PositiveSmallIntegerField(choices=[(0, 'mass%'), (1, 'atom%')], default=0, verbose_name='Percent in')),
                ('template', models.BooleanField(default=False, verbose_name='Template')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.sample', verbose_name='Sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('element', models.PositiveSmallIntegerField(choices=[(1, 'H'), (2, 'He'), (3, 'Li'), (4, 'Be'), (5, 'B'), (6, 'C'), (7, 'N'), (8, 'O'), (9, 'F'), (10, 'Ne'), (11, 'Na'), (12, 'Mg'), (13, 'Al'), (14, 'Si'), (15, 'P'), (16, 'S'), (17, 'Cl'), (18, 'Ar'), (19, 'K'), (20, 'Ca'), (21, 'Sc'), (22, 'Ti'), (23, 'V'), (24, 'Cr'), (25, 'Mn'), (26, 'Fe'), (27, 'Co'), (28, 'Ni'), (29, 'Cu'), (30, 'Zn'), (31, 'Ga'), (32, 'Ge'), (33, 'As'), (34, 'Se'), (35, 'Br'), (36, 'Kr'), (37, 'Rb'), (38, 'Sr'), (39, 'Y'), (40, 'Zr'), (41, 'Nb'), (42, 'Mo'), (43, 'Tc'), (44, 'Ru'), (45, 'Rh'), (46, 'Pd'), (47, 'Ag'), (48, 'Cd'), (49, 'In'), (50, 'Sn'), (51, 'Sb'), (52, 'Te'), (53, 'I'), (54, 'Xe'), (55, 'Cs'), (56, 'Ba'), (57, 'La'), (58, 'Ce'), (59, 'Pr'), (60, 'Nd'), (61, 'Pm'), (62, 'Sm'), (63, 'Eu'), (64, 'Gd'), (65, 'Tb'), (66, 'Dy'), (67, 'Ho'), (68, 'Er'), (69, 'Tm'), (70, 'Yb'), (71, 'Lu'), (72, 'Hf'), (73, 'Ta'), (74, 'W'), (75, 'Re'), (76, 'Os'), (77, 'Ir'), (78, 'Pt'), (79, 'Au'), (80, 'Hg'), (81, 'Tl'), (82, 'Pb'), (83, 'Bi'), (84, 'Po'), (85, 'At'), (86, 'Rn'), (87, 'Fr'), (88, 'Ra'), (89, 'Ac'), (90, 'Th'), (91, 'Pa'), (92, 'U'), (93, 'Np'), (94, 'Pu')], verbose_name='Element')),
                ('fraction', models.FloatField(blank=True, null=True, verbose_name='Fraction')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material', verbose_name='Material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
