# Generated by Django 4.2 on 2024-02-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Valid'), (1, 'Invalid'), (2, 'Pending')], default=0, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('ncol', models.PositiveSmallIntegerField(default=1, verbose_name='N Column')),
                ('margin', models.PositiveSmallIntegerField(default=0, verbose_name='Margin')),
                ('bgcolor', models.PositiveSmallIntegerField(choices=[(0, 'White'), (1, 'Olive'), (2, 'Yellow'), (3, 'Fuchsia'), (4, 'Silver'), (5, 'Aqua'), (6, 'Lime'), (7, 'Red'), (8, 'Gray'), (9, 'Blue'), (10, 'Green'), (11, 'Purple'), (12, 'Black'), (13, 'Navy'), (14, 'Teal'), (15, 'Maroon')], default=0, verbose_name='BG Color')),
                ('format', models.PositiveSmallIntegerField(choices=[(0, 'JPEG'), (1, 'PNG')], default=0, verbose_name='Format')),
                ('file', models.ImageField(blank=True, null=True, upload_to=project.models.ModelUploadTo, verbose_name='Image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('remoteid', models.IntegerField(blank=True, null=True, verbose_name='Remote ID')),
                ('remoteat', models.DateTimeField(blank=True, null=True, verbose_name='Remote updated at')),
                ('localupd', models.BooleanField(default=False, verbose_name='Local updated')),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
                ('shiftx', models.SmallIntegerField(default=0, verbose_name='Shift X')),
                ('shifty', models.SmallIntegerField(default=0, verbose_name='Shift Y')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album', verbose_name='Album')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.models.FileSearch),
        ),
    ]
