# Generated by Django 4.2 on 2024-05-21 08:21

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='unique',
            field=models.CharField(default=project.models.UniqueID, max_length=36, verbose_name='Unique ID'),
        ),
    ]
