# Generated by Django 4.2 on 2025-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_prefix_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remoteauth',
            field=models.CharField(blank=True, max_length=10, verbose_name='Remote auth'),
        ),
        migrations.AddField(
            model_name='project',
            name='remotelink',
            field=models.URLField(blank=True, verbose_name='Remote link'),
        ),
        migrations.AddField(
            model_name='project',
            name='remotelog',
            field=models.TextField(blank=True, verbose_name='Remote log'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Task ID'),
        ),
    ]
