# Generated by Django 4.2 on 2025-03-07 23:44

from django.db import migrations, models
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='publicfile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=public.models.PublicUploadTo, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='publicfile',
            name='header',
            field=models.BooleanField(default=False, verbose_name='Header'),
        ),
    ]
