# Generated by Django 4.2 on 2024-05-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curve',
            name='endid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='End Index'),
        ),
        migrations.AddField(
            model_name='curve',
            name='startid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Index'),
        ),
    ]
