# Generated by Django 4.2 on 2024-05-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0002_curve_endid_curve_startid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregate',
            name='prefix',
            field=models.CharField(blank=True, max_length=36, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='curve',
            name='prefix',
            field=models.CharField(blank=True, max_length=36, verbose_name='Prefix'),
        ),
    ]
