# Generated by Django 4.2 on 2025-03-07 23:44

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0004_filter_unique_value_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='sheetname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sheet name'),
        ),
        migrations.AlterField(
            model_name='value',
            name='file',
            field=models.FileField(upload_to=project.models.ModelUploadTo, verbose_name='Value file (.csv, .xlsx)'),
        ),
    ]
